- 03:
  - name_ja: "上村莉菜"
    name_ja_hiragana: "うえむらりな"
    name_en: "Rina Uemura"
  - gen: 1st
- 06:
  - name_ja: "小池美波"
    name_ja_hiragana: "こいけみなみ"
    name_en: "Minami Koike"
  - gen: 1st
- 07:
  - name_ja: "小林由依"
    name_ja_hiragana: "こばやしゆい"
    name_en: "Yui Kobayashi"
  - gen: 1st
- 8:
  - name_ja: "齋藤冬優花"
    name_ja_hiragana: "さいとうふゆか"
    name_en: "Fuyuka Saito"
  - gen: 1st
- 14:
  - name_ja: "土生瑞穂"
    name_ja_hiragana: "はぶみづほ"
    name_en: "Mizuho Habu"
  - gen: 1st
- 43:
  - name_ja: "井上梨名"
    name_ja_hiragana: "いのうえりな"
    name_en: "Rina Inoue"
  - gen: 2nd
- 53:
  - name_ja: "遠藤光莉"
    name_ja_hiragana: "えんどうひかり"
    name_en: "Hikari Endo"
  - gen: 2nd
- 54:
  - name_ja: "大園玲"
    name_ja_hiragana: "おおぞのれい"
    name_en: "Rei Ozono"
  - gen: 2nd
- 55:
  - name_ja: "大沼晶保"
    name_ja_hiragana: "おおぬまおきほ"
    name_en: "Akiho Onuma"
  - gen: 2nd
- 56:
  - name_ja: "幸坂茉里乃"
    name_ja_hiragana: "こうさかまりの"
    name_en: "Marino Kosaka"
  - gen: 2nd
- 45:
  - name_ja: "武元唯衣"
    name_ja_hiragana: "たけもとゆい"
    name_en: "Yui Takemoto"
  - gen: 2nd
- 46:
  - name_ja: "田村保乃"
    name_ja_hiragana: "たむらほの"
    name_en: "Hono Tamura"
  - gen: 2nd
- 47:
  - name_ja: "藤吉夏鈴"
    name_ja_hiragana: "ふじよしかりん"
    name_en: "Karin Fujiyoshi"
  - gen: 2nd
- 57:
  - name_ja: "増本綺良"
    name_ja_hiragana: "ますもときら"
    name_en: "Kira Masumoto"
  - gen: 2nd
- 48:
  - name_ja: "松田里奈"
    name_ja_hiragana: "まつだりな"
    name_en: "Rina Matsuda"
  - gen: 2nd
- 50:
  - name_ja: "森田ひかる"
    name_ja_hiragana: "もりたひかる"
    name_en: "Hikaru Morita"
  - gen: 2nd
- 58:
  - name_ja: "守屋麗奈"
    name_ja_hiragana: "もりやれな"
    name_en: "Rena Moriya"
  - gen: 2nd
- 57:
  - name_ja: "山﨑天"
    name_ja_hiragana: "やまさきてん"
    name_en: "Ten Yamasaki"
  - gen: 2nd
- 59:
  - name_ja: "石森璃花"
    name_ja_hiragana: "いしもりりか"
    name_en: "Rika Ishimori"
  - gen: 3rd
- 60:
  - name_ja: "遠藤理子"
    name_ja_hiragana: "えんどうりこ"
    name_en: "Riko Endo"
  - gen: 3rd
- 61:
  - name_ja: "小田倉麗奈"
    name_ja_hiragana: "おだくられいな"
    name_en: "Reina Odakura"
  - gen: 3rd
- 62:
  - name_ja: "小島凪紗"
    name_ja_hiragana: "こじまなぎさ"
    name_en: "Nagisa Kojima"
  - gen: 3rd
- 63:
  - name_ja: "谷口愛梨"
    name_ja_hiragana: "たにぐちあいり"
    name_en: "Airi Taniguchi"
  - gen: 3rd
- 64:
  - name_ja: "中島優月"
    name_ja_hiragana: "なかしまゆづき"
    name_en: "Yuzuki Nakashima"
  - gen: 3rd
- 65:
  - name_ja: "的野美青"
    name_ja_hiragana: "まとのみお"
    name_en: "Mio Matono"
  - gen: 3rd
- 66:
  - name_ja: "向井純葉"
    name_ja_hiragana: "むかいいとは"
    name_en: "Itoha Mukai"
  - gen: 3rd
- 67:
  - name_ja: "村井優"
    name_ja_hiragana: "むらいゆう"
    name_en: "Yu Murai"
  - gen: 3rd
- 68:
  - name_ja: "村山美羽"
    name_ja_hiragana: "むらやまみう"
    name_en: "Miu Murayama"
  - gen: 3rd
- 69:
  - name_ja: "山下瞳月"
    name_ja_hiragana: "やましたしづき"
    name_en: "Shizuki Yamashita"
  - gen: 3rd