hinatazaka:
  blog_top_page: "https://www.hinatazaka46.com/s/official/diary/member?ima=0000"
  blog_list_page: "https://www.hinatazaka46.com/s/official/diary/member/list?ima=0000"
sakurazaka:
  blog_top_page: "https://sakurazaka46.com/s/s46/diary/blog"
  blog_list_page: "https://sakurazaka46.com/s/s46/diary/blog/list"
  exclude_img_path:
    - /files/14/s46/img/com-logo_pc.svg
    - /files/14/s46/img/jasrac.jpg
keyakizaka:
