hinatazaka:
  blog_top_page: "https://www.hinatazaka46.com/s/official/diary/member?ima=0000"
  blog_list_page: "https://www.hinatazaka46.com/s/official/diary/member/list?ima=0000"
sakurazaka:

keyakizaka:
